### PR TITLE
fix: prevent link-time openssl symbols conflicts

### LINKED ISSUE #9: Symbol conflicts with vendored `openssl` can cause invalid outputs
See https://github.com/alloy-rs/core/issues/711.

---
https://github.com/alloy-rs/core/issues/711#issuecomment-2298830376:

Reduced:

src/main.rs
```rust
extern crate alloy_primitives;
extern crate openssl;

fn main() {
    assert_eq!(
        alloy_primitives::keccak256("testFoo()"),
        alloy_primitives::b256!("79adbd5094e60c1bc2b963678ff44695d1430b8ccff0b1cd57c03a7f63567822"),
    );
}
```

Cargo.toml
```toml
[package]
name = "foundry-zksync-release-debug"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { version = "0.7", default-features = false }
openssl = { version = "0.10", features = ["vendored"] }

[features]
asm-keccak = ["alloy-primitives/asm-keccak"]
```

---

Running `cargo run --features asm-keccak` panics.

Applying this patch makes the command run fine again:
```diff
diff --git a/src/main.rs b/src/main.rs
index c82c4a9..1ae767f 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -1,5 +1,5 @@
-extern crate alloy_primitives;
 extern crate openssl;
+extern crate alloy_primitives;
 
 fn main() {
     assert_eq!(
```

---

I am not sure how to fix this, it seems like it's a symbol conflict between the vendored openssl static library and keccak-asm's.

### PR DESCRIPTION
**Pull request by Rjected**
Renames the symbols by preprocessing, to prevent conflicts when both sha3-asm are used as a dependency. Previously the symbols would conflict, for example by running:
```
RUSTC_LOG=rustc_codegen_ssa::back::link=info RUSTFLAGS="-C link-arg=-Wl,-warn_duplicate_libraries,-why_load,-all_load" cargo build --features asm-keccak
```
on a repo with both `alloy-primitives` with the keccak feature enabled, and an openssl dependency. Previously we would get symbol conflicts:
```
          duplicate symbol '_SHA3_absorb_cext' in:
              /Users/dan/projects/test-repro-keccak/target/debug/deps/libsha3_asm-62b37d0448a71d41.rlib[4](99b77fa459c7b68d-keccak1600-armv8.o)
              /Users/dan/projects/test-repro-keccak/target/debug/deps/libopenssl_sys-ce87998bbf8dc503.rlib[716](libcrypto-lib-keccak1600-armv8.o)
          duplicate symbol '_SHA3_squeeze_cext' in:
              /Users/dan/projects/test-repro-keccak/target/debug/deps/libsha3_asm-62b37d0448a71d41.rlib[4](99b77fa459c7b68d-keccak1600-armv8.o)
              /Users/dan/projects/test-repro-keccak/target/debug/deps/libopenssl_sys-ce87998bbf8dc503.rlib[716](libcrypto-lib-keccak1600-armv8.o)
          duplicate symbol '_SHA3_squeeze' in:
              /Users/dan/projects/test-repro-keccak/target/debug/deps/libsha3_asm-62b37d0448a71d41.rlib[4](99b77fa459c7b68d-keccak1600-armv8.o)
              /Users/dan/projects/test-repro-keccak/target/debug/deps/libopenssl_sys-ce87998bbf8dc503.rlib[716](libcrypto-lib-keccak1600-armv8.o)
          duplicate symbol '_SHA3_absorb' in:
              /Users/dan/projects/test-repro-keccak/target/debug/deps/libsha3_asm-62b37d0448a71d41.rlib[4](99b77fa459c7b68d-keccak1600-armv8.o)
              /Users/dan/projects/test-repro-keccak/target/debug/deps/libopenssl_sys-ce87998bbf8dc503.rlib[716](libcrypto-lib-keccak1600-armv8.o)
          ld: 4 duplicate symbols
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

With this, the previous command passes, see the renamed symbols here:
```
dan@Dans-MacBook-Pro-4 ~/p/keccak-asm (dan/rename-functions)> nm --debug-syms target/debug/build/sha3-asm-8f6b07d072c05e01/out/libkeccak.a

dd311508d4385923-keccak1600-armv8.o:
0000000000000340 t KeccakF1600
00000000000006e0 t KeccakF1600_ce
0000000000000800 t KeccakF1600_cext
0000000000000100 t KeccakF1600_int
0000000000000420 T _KECCAK_ASM_SHA3_absorb
00000000000008c0 T _KECCAK_ASM_SHA3_absorb_cext
0000000000000600 T _KECCAK_ASM_SHA3_squeeze
0000000000000a20 T _KECCAK_ASM_SHA3_squeeze_cext
0000000000000040 t iotas
0000000000000000 t ltmp0
0000000000000d64 s ltmp1
```

on non-darwin, we have to add macros for no leading underscores:
```
ubuntu@reth3:~/keccak-asm dan/rename-functions $ nm --debug-syms target/debug/build/sha3-asm-1fbd5b7ac64af10f/out/libkeccak.a

fd027825897661df-keccak1600-x86_64.o:
0000000000000000 N .debug_abbrev
0000000000000000 N .debug_info
0000000000000000 N .debug_line
0000000000000000 N .debug_str
0000000000000000 t .text
0000000000000380 T KECCAK_ASM_SHA3_absorb
0000000000000460 T KECCAK_ASM_SHA3_squeeze
00000000000002e0 T KeccakF1600
0000000000000000 t __KeccakF1600
0000000000000540 t iotas
```

Closes #9

### CODE REVIEW

File: sha3-asm/build.rs [hunk 1]
```diff
@@ -18,7 +18,24 @@ fn main() {
     if target.is_any_arm() {
         cc.include("cryptogams/arm");
     }
-    cc.file(sha3).compile("keccak");
+    cc.file(sha3)
+        .flag("-D")
```
Comment (DaniPopes) [inline sha3-asm/build.rs]: should make this programmatic with an array/forloop, also needs /D instead of -D for MSVC

File: sha3-asm/src/lib.rs [hunk 2]
```diff
@@ -20,7 +20,7 @@ extern "C" {
     /// size_t SHA3_absorb(uint64_t A[5][5], const unsigned char *inp, size_t len,
     ///                    size_t r);
     /// ```
-    pub fn SHA3_absorb(a: *mut Buffer, inp: *const u8, len: usize, r: usize) -> usize;
+    pub fn KECCAK_ASM_SHA3_absorb(a: *mut Buffer, inp: *const u8, len: usize, r: usize) -> usize;
```
Comment (DaniPopes) [inline sha3-asm/src/lib.rs]: can avoid renaming by using `#[link_name = ""]`

**Review by DaniPopes — CHANGES_REQUESTED** [review]

File: sha3-asm/src/lib.rs (hunk 2 above)
Comment (Rjected) [reply sha3-asm/src/lib.rs]: ah nice, didn't know this was a thing

File: sha3-asm/build.rs [hunk 3]
```diff
@@ -14,11 +14,46 @@ fn main() {
     eprintln!("selected cryptogams script flavor: {flavor:?}");
     run_perlasm(script, flavor.as_deref(), &sha3);
 
+    // MSVC's provided arm assembler does not support -D, only allowing PreDefine to be used.
+    // Unfortunately these are subtly different from -D, making them difficult to use when there
+    // might be symbol conflicts.
+    //
+    // Instead, we will do a find/replace on the assembly here.
+    if target.is_msvc() && target.is_any_arm() {
```
Comment (DaniPopes) [inline sha3-asm/build.rs]: Can you move this to before `compile()`, and use the same array to do `.replace` on the string? Order of args shouldn't matter

File: sha3-asm/build.rs [hunk 4]
```diff
@@ -14,11 +14,46 @@ fn main() {
...
+
+    let preprocessor_renames = [
+        ("SHA3_squeeze_cext", "KECCAK_ASM_SHA3_squeeze_cext"),
+        ("SHA3_absorb_cext", "KECCAK_ASM_SHA3_absorb_cext"),
+        ("SHA3_squeeze", "KECCAK_ASM_SHA3_squeeze"),
+        ("SHA3_absorb", "KECCAK_ASM_SHA3_absorb"),
+        ("_SHA3_squeeze", "_KECCAK_ASM_SHA3_squeeze"),
+        ("_SHA3_absorb", "_KECCAK_ASM_SHA3_absorb"),
+        ("_SHA3_squeeze_cext", "_KECCAK_ASM_SHA3_squeeze_cext"),
+        ("_SHA3_absorb_cext", "_KECCAK_ASM_SHA3_absorb_cext"),
```
Comment (DaniPopes) [inline sha3-asm/build.rs]: can derive .1 with `"{prefix}{.0}"`

File: sha3-asm/build.rs (hunk 3 above)
Comment (Rjected) [reply sha3-asm/build.rs]: the leading underscore renames would rename / match previously renamed `KECCAK_ASM_SHA3_absorb`, so I'm not sure `replace`ing with the same array is a good idea. But this can be moved before `compile`

Comment (Rjected) [reply sha3-asm/build.rs]: figured something out

**Review by DaniPopes — APPROVED** [review]
:saluting_face:
